from __future__ import annotations

import json
import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCENE_STORIES_DIR = PROJECT_ROOT / "scene_storyies"
BACKEND_OUTPUT_PATH = PROJECT_ROOT / "backend" / "app" / "generated" / "scene_specs.json"
FRONTEND_OUTPUT_PATH = PROJECT_ROOT / "frontend" / "src" / "generated" / "scene_specs.ts"

SCENE_SPEC_BLOCK_RE = re.compile(r"```scene-spec\s*\n(?P<body>.*?)\n```", re.DOTALL)
REQUIRED_KEYS = {
    "scene_id",
    "scene_name",
    "company",
    "tagline",
    "role_id",
    "role_label",
    "role_hint",
    "opening_line",
    "salary_anchor",
    "initial_state",
    "score_profile",
    "tone_map",
    "strategy_delta_map",
    "traps",
}


def main() -> None:
    scene_specs = sorted(
        (_parse_scene_story(path) for path in SCENE_STORIES_DIR.glob("scenario-*.md")),
        key=lambda item: item["scene_id"],
    )

    if not scene_specs:
        raise SystemExit("No scene story markdown files were found.")

    backend_payload = {
        "generated_from": "scene_storyies/*.md",
        "scenes": scene_specs,
    }
    _write_backend_json(backend_payload)
    _write_frontend_ts(scene_specs)
    print(f"Generated {len(scene_specs)} scene specs.")


def _parse_scene_story(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = SCENE_SPEC_BLOCK_RE.search(text)
    if not match:
        raise ValueError(f"{path} is missing a scene-spec block")

    spec = json.loads(match.group("body"))
    missing = REQUIRED_KEYS - set(spec)
    if missing:
        raise ValueError(f"{path} is missing required keys: {', '.join(sorted(missing))}")

    spec["source_path"] = str(path.relative_to(PROJECT_ROOT)).replace("\\", "/")
    return spec


def _write_backend_json(payload: dict) -> None:
    BACKEND_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    BACKEND_OUTPUT_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _write_frontend_ts(scene_specs: list[dict]) -> None:
    FRONTEND_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    scene_options = [
        {
            "sceneId": item["scene_id"],
            "roleId": item["role_id"],
            "label": item["scene_name"],
            "company": item["company"],
            "tagline": item["tagline"],
            "roleLabel": item["role_label"],
        }
        for item in scene_specs
    ]
    frontend_specs = [
        {
            "sceneId": item["scene_id"],
            "sceneName": item["scene_name"],
            "company": item["company"],
            "tagline": item["tagline"],
            "roleId": item["role_id"],
            "roleLabel": item["role_label"],
            "roleHint": item["role_hint"],
            "openingLine": item["opening_line"],
            "initialState": item["initial_state"],
            "traps": item["traps"],
        }
        for item in scene_specs
    ]
    options_payload = json.dumps(scene_options, ensure_ascii=False, indent=2)
    specs_payload = json.dumps(frontend_specs, ensure_ascii=False, indent=2)
    FRONTEND_OUTPUT_PATH.write_text(
        "// AUTO-GENERATED by scripts/build_scene_specs.py. Do not edit manually.\n"
        f"export const GENERATED_SCENE_OPTIONS = {options_payload} as const;\n\n"
        f"export const GENERATED_SCENE_SPECS = {specs_payload} as const;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
